// hs_clipboard-gt — a history of what has been copied, offered back through a chooser.
//
// A port of ClipboardTool.spoon (Alfred Schilken, MIT), itself derived from
// TextClipboardHistory.spoon and from code by VFS and asmagill, plus the password
// detection added to the local copy of it.
//
//     const clipboard = hs.loadSpoon("hs_clipboard-gt")
//     clipboard.start()
//     hs.hotkey.bind(hyper, "v", () => clipboard.historyShow(), null)
//
// Every string that reaches the pasteboard is prepended to the history, duplicates are
// collapsed by MD5, and the list is capped at config.historySize. Selecting an entry
// copies it back, and optionally types ⌘V into whatever window had focus.
//
// Entries that look like passwords are kept for the session but are never written to
// disk, and are shown as "[hidden - N chars]" until revealed with ⌘R (the selected row)
// or ⇧⌘R (all of them). Detection runs in three steps — an allowlist of shapes that are
// never passwords, a structural filter, and a Shannon entropy threshold — so that URLs,
// UUIDs, hashes and filenames are not masked.
//
// Four departures from the v1 Spoon:
//   * Changes arrive through hs.pasteboard.addWatcher rather than a timer of the Spoon's
//     own, so config.watchInterval sets the interval of the shared pasteboard watcher.
//   * The history is a JSON file under logs/, not an entry in the application defaults.
//   * Images are not stored. v1 kept them URL-encoded in the same list.
//   * There is no hs.dialog, so an entry longer than config.maxEntrySize is truncated
//     when it is stored instead of prompting. v1's max-size toggle is gone with it.

// MARK: - User-configurable settings

const config = {
    // Seconds between pasteboard samples. This is a property of the shared watcher, so
    // the last module to set it wins.
    watchInterval: 0.8,

    // How many entries to keep, and how much of one.
    historySize: 100,
    maxEntrySize: 4990,

    // Characters of an entry shown in the chooser. The whole entry is copied when it is
    // selected; only the row is shortened.
    displayMaxLength: 200,

    // Whether an entry identical to one already held replaces it instead of joining it.
    deduplicate: true,

    // Whether copying announces itself, and for how long.
    copiedAlert: true,
    alertDuration: 1,

    // Whether to consult the pasteboard's data types and ignore the entry when one of
    // them is in ignoredIdentifiers. The list comes from http://nspasteboard.org.
    honorIgnoredIdentifiers: true,
    ignoredIdentifiers: [
        "de.petermaurer.TransientPasteboardType", // Transient: Textpander, TextExpander, Butler
        "com.typeit4me.clipping",                 // Transient: TypeIt4Me
        "Pasteboard generator type",              // Transient: Typinator
        "com.agilebits.onepassword",              // Confidential: 1Password
        "org.nspasteboard.TransientType",         // Universal, transient
        "org.nspasteboard.ConcealedType",         // Universal, concealed
        "org.nspasteboard.AutoGeneratedType"      // Universal, automatic
    ],

    // Password-like entries: masked in the chooser and never persisted. Setting this to
    // false persists everything and masks nothing.
    passwordsHide: true,
    passwordEntropyThreshold: 3.5,
    passwordMinLength: 8,
    passwordMaxNewlines: 1,

    // Chords that reveal a masked entry, active only while the chooser is on screen.
    revealCurrentKey: {mods: ["cmd"], key: "r"},
    revealAllKey: {mods: ["cmd", "shift"], key: "r"},

    // Seconds to wait after the chooser closes before typing, so that the keystrokes
    // arrive at the window that has just regained focus.
    pasteDelay: 0.2,

    // The menubar item, which opens the history when clicked.
    menubarShow: true,
    menubarTitle: "📋",

    historyFile: `${hs.appinfo.configDir}/logs/clipboard.json`
}

// MARK: - State

// [{type: "text", content: "..."}], most recent first.
let history = []

// Whether selecting an entry also types ⌘V. Persisted alongside the history.
let pasteOnSelect = false

let chooser = null
let menubarItem = null
let watcher = null

// The window that had focus when the chooser was shown. The chooser takes focus itself,
// so anything typed afterwards needs it restored first.
let previousWindow = null

// Reveal state, reset every time the chooser closes.
let revealAll = false
let revealedRow = null
let revealCurrentHotkey = null
let revealAllHotkey = null

// MARK: - Password detection

// Shannon entropy of a string, in bits per character.
function passwordEntropy(text) {
    if (!text || text.length === 0) return 0

    const counts = new Map()
    for (const character of text) counts.set(character, (counts.get(character) || 0) + 1)

    let entropy = 0
    for (const count of counts.values()) {
        const p = count / text.length
        entropy -= p * Math.log2(p)
    }
    return entropy
}

const PASSWORD_SYMBOLS = /[!@#$%^&*()\-_=+[\]{}|;:',.<>?/\\`~"]/
// Above this share of digits, or of hex characters, a string is an identifier of some
// kind rather than a password.
const PASSWORD_MOSTLY = 0.70

// Step 1: shapes that are never masked, however random they look.
function passwordAllowlisted(text) {
    const length = text.length

    if ((text.match(/\n/g) || []).length > config.passwordMaxNewlines) return true

    // UUID.
    if (/^[0-9a-fA-F]{1,8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/.test(text)) return true
    // ULID: 26 characters of Crockford Base32.
    if (length === 26 && /^[0-9A-HJKMNP-TV-Z]+$/.test(text)) return true
    // MD5, SHA1 or SHA256 written out in hex.
    if ((length === 32 || length === 40 || length === 64) && /^[0-9a-fA-F]+$/.test(text)) return true
    // Base64 with padding.
    if (length % 4 === 0 && /=+$/.test(text) && /^[A-Za-z0-9+/]+=*$/.test(text)) return true
    // A number.
    if (/^-?[0-9]+\.?[0-9]*$/.test(text)) return true
    // An ISO date, with or without a time after it.
    if (/^\d{4}-\d{2}-\d{2}/.test(text)) return true
    // IPv4, and IPv6 taken as hex with at least two colons in it.
    if (/^\d+\.\d+\.\d+\.\d+$/.test(text)) return true
    if (/^[0-9a-fA-F:]+$/.test(text) && /:.*:/.test(text)) return true
    // A URL, a path, or a bare filename.
    if (text.includes("://")) return true
    if (text.includes("/")) return true
    if (/\.[a-zA-Z0-9]+$/.test(text) && !/\s/.test(text)) return true

    return false
}

// Step 2: long enough, unbroken, and mixed enough to be a password.
function passwordStructured(text) {
    const length = text.length
    if (length < config.passwordMinLength) return false
    if (/\s/.test(text)) return false

    let digits = 0
    let hex = 0
    let lower = false
    let upper = false
    let digit = false
    let symbol = false

    for (const character of text) {
        if (/[0-9]/.test(character)) {
            digits += 1
            hex += 1
            digit = true
        } else if (/[a-f]/.test(character)) {
            hex += 1
            lower = true
        } else if (/[A-F]/.test(character)) {
            hex += 1
            upper = true
        } else if (/[a-z]/.test(character)) {
            lower = true
        } else if (/[A-Z]/.test(character)) {
            upper = true
        } else if (PASSWORD_SYMBOLS.test(character)) {
            symbol = true
        }
    }

    if (digits / length >= PASSWORD_MOSTLY) return false
    if (hex / length >= PASSWORD_MOSTLY) return false

    const classes = [lower, upper, digit, symbol].filter(Boolean).length
    return classes >= 2
}

// All three steps. Only a string that clears every one of them is treated as a password.
function passwordLike(text) {
    if (typeof text !== "string" || text === "") return false
    if (passwordAllowlisted(text)) return false
    if (!passwordStructured(text)) return false
    return passwordEntropy(text) >= config.passwordEntropyThreshold
}

// MARK: - Persistence

function historyLoad() {
    if (!hs.fs.exists(config.historyFile)) return

    const body = hs.fs.read(config.historyFile, 0, 0)
    if (!body || body === "") return

    let data = null
    try {
        data = JSON.parse(body)
    } catch (error) {
        console.error(`[hs_clipboard-gt] ${config.historyFile} is unreadable, starting fresh: ${error}`)
        return
    }
    if (!data || typeof data !== "object") return

    pasteOnSelect = data.pasteOnSelect === true
    history = historyPrune(Array.isArray(data.items) ? data.items : [])
}

// Password-like entries live in memory only, so they are dropped on the way out. This
// also scrubs any that an earlier version of the Spoon, or of its v1 ancestor, wrote.
function historySave() {
    const items = config.passwordsHide
        ? history.filter((entry) => !passwordLike(entry.content))
        : history
    hs.fs.write(config.historyFile,
        JSON.stringify({pasteOnSelect: pasteOnSelect, items: items}, null, 2), false)
}

// MARK: - The history itself

// Discards malformed entries, collapses duplicates and applies the size cap. The first
// of a set of duplicates wins, so the most recent copy keeps its place at the top.
function historyPrune(list) {
    const result = []
    const seen = new Set()

    for (const entry of list) {
        if (result.length >= config.historySize) break
        if (!entry || entry.type !== "text" || typeof entry.content !== "string") continue

        const hash = hs.hashing.md5(entry.content)
        if (config.deduplicate && seen.has(hash)) continue

        seen.add(hash)
        result.push({type: "text", content: entry.content})
    }
    return result
}

// Cuts an over-long entry at the last blank line that fits, and failing that at the
// limit itself.
function contentTruncate(text) {
    if (text.length <= config.maxEntrySize) return text

    const paragraph = text.lastIndexOf("\n\n", config.maxEntrySize)
    return paragraph > 0 ? text.slice(0, paragraph) : text.slice(0, config.maxEntrySize)
}

function historyAdd(text) {
    history.unshift({type: "text", content: text})
    history = historyPrune(history)
    historySave()
}

// MARK: - Reading the pasteboard

function pasteboardIgnored() {
    if (!config.honorIgnoredIdentifiers) return false
    return (hs.pasteboard.types() || []).some((type) => config.ignoredIdentifiers.includes(type))
}

function pasteboardCapture() {
    if (pasteboardIgnored()) return

    const content = hs.pasteboard.readString()
    if (content === null || content === undefined || content === "") return

    // Selecting an entry writes it back to the pasteboard, which arrives here as a
    // change of its own. Nothing has been copied, so there is nothing to announce.
    if (history.length > 0 && history[0].content === content) return

    const stored = contentTruncate(content)
    historyAdd(stored)

    if (!config.copiedAlert) return
    const masked = config.passwordsHide && passwordLike(stored)
    const note = masked ? " (password-like, not persisted)" : ""
    const shortened = stored.length < content.length ? ` of ${content.length}` : ""
    hs.ui.alert(`Copied ${stored.length}${shortened} chars${note}`).duration(config.alertDuration).show()
}

// MARK: - Typing and pasting

// The chooser holds focus while it is up, so anything typed has to wait for the window
// underneath to have it back.
function windowRestore(then) {
    if (chooser && chooser.isVisible) chooser.hide()
    if (previousWindow) previousWindow.focus()
    hs.timer.doAfter(config.pasteDelay, then)
}

// v1's "paste all with delimiter": every entry from the given row up to the newest one,
// typed out oldest first, each followed by the delimiter.
function entriesPaste(row, delimiter) {
    const entries = history.slice(0, row + 1).reverse()
    windowRestore(() => {
        for (const entry of entries) {
            hs.eventtap.keyStrokes(entry.content)
            hs.eventtap.keyStrokes(delimiter)
        }
    })
}

// MARK: - Rearranging entries

function entryDelete(row) {
    if (row < 0 || row >= history.length) return module.exports
    history.splice(row, 1)
    historySave()
    chooserRefresh()
    return module.exports
}

function entryMove(row, destination) {
    if (row < 0 || row >= history.length) return module.exports
    const target = Math.min(Math.max(destination, 0), history.length - 1)
    if (target === row) return module.exports

    const [entry] = history.splice(row, 1)
    history.splice(target, 0, entry)
    historySave()
    chooserRefresh()
    return module.exports
}

function entryMoveToTop(row) { return entryMove(row, 0) }
function entryMoveUp(row) { return entryMove(row, row - 1) }
function entryMoveDown(row) { return entryMove(row, row + 1) }

// Reverses the order of everything from the newest entry down to the given row, which is
// what v1 offered for turning a set of copies back into the order they were made in.
function entriesInvert(row) {
    if (row < 0 || row >= history.length) return module.exports
    const head = history.slice(0, row + 1).reverse()
    history = head.concat(history.slice(row + 1))
    historySave()
    chooserRefresh()
    return module.exports
}

function historyClear() {
    hs.pasteboard.clear()
    history = []
    historySave()
    chooserRefresh()
    return module.exports
}

function historyLastDelete() {
    return entryDelete(0)
}

// MARK: - Paste-on-select

function pasteOnSelectToggle() {
    pasteOnSelect = !pasteOnSelect
    historySave()
    hs.ui.alert(`Paste-on-select is now ${pasteOnSelect ? "enabled" : "disabled"}`)
        .duration(config.alertDuration).show()
    return pasteOnSelect
}

// MARK: - Revealing masked entries

function revealReset() {
    revealAll = false
    revealedRow = null
}

// ⌘R: reveal the selected row, or hide it again if it is the one already revealed.
function passwordRevealCurrent() {
    if (!chooser) return module.exports
    const row = chooser.selectedRow
    if (row === null || row === undefined || row < 0) return module.exports

    revealedRow = revealedRow === row ? null : row
    chooserRefresh()
    chooser.selectedRow = row
    return module.exports
}

// ⇧⌘R: reveal every masked entry, or mask them all again.
function passwordsRevealToggle() {
    if (!chooser) return module.exports
    const row = chooser.selectedRow

    revealAll = !revealAll
    revealedRow = null
    chooserRefresh()
    if (row !== null && row !== undefined && row >= 0) chooser.selectedRow = row
    return module.exports
}

function revealKeysEnable() {
    if (revealCurrentHotkey) revealCurrentHotkey.enable()
    if (revealAllHotkey) revealAllHotkey.enable()
}

function revealKeysDisable() {
    if (revealCurrentHotkey) revealCurrentHotkey.disable()
    if (revealAllHotkey) revealAllHotkey.disable()
}

// MARK: - The chooser

// Right-clicking a row offers what v1 put behind its own context menu. The row is fixed
// when the menu is built, so every action closes over it.
function entryContextMenu(row) {
    return [
        {title: "Paste all up to here, tab separated", action: () => entriesPaste(row, "\t")},
        {title: "Paste all up to here, one per line", action: () => entriesPaste(row, "\n")},
        {type: "divider"},
        {title: "Delete entry", action: () => entryDelete(row)},
        {title: "Move entry to top", action: () => entryMoveToTop(row)},
        {title: "Move entry up", action: () => entryMoveUp(row)},
        {title: "Move entry down", action: () => entryMoveDown(row)},
        {title: "Invert order above", action: () => entriesInvert(row)}
    ]
}

function chooserChoices() {
    const choices = []

    history.forEach((entry, row) => {
        const masked = config.passwordsHide && passwordLike(entry.content)
        const revealed = revealAll || revealedRow === row
        const text = (masked && !revealed)
            ? `[hidden - ${entry.content.length} chars]`
            : entry.content.slice(0, config.displayMaxLength)

        choices.push({
            text: text,
            action: "paste",
            data: entry.content,
            row: row,
            contextMenu: entryContextMenu(row)
        })
    })

    if (choices.length === 0) {
        choices.push({
            text: "",
            subText: "《Clipboard is empty》",
            action: "none",
            image: HSImage.fromName("NSCaution")
        })
    } else {
        choices.push({
            text: "《Clear Clipboard History》",
            action: "clear",
            image: HSImage.fromName("NSTrashFull")
        })
    }

    choices.push({
        text: `《${pasteOnSelect ? "Disable" : "Enable"} Paste-on-select》`,
        action: "pasteOnSelect",
        // v1 used NSSwitchEnabledOn/Off, which this macOS no longer resolves.
        image: HSImage.fromSymbol(pasteOnSelect ? "checkmark.circle.fill" : "circle")
    })

    return choices
}

function chooserRefresh() {
    if (chooser) chooser.setChoices(chooserChoices())
    return module.exports
}

function chooserSelect(choice) {
    revealKeysDisable()
    revealReset()

    if (!choice) return

    if (choice.action === "clear") {
        historyClear()
        return
    }
    if (choice.action === "pasteOnSelect") {
        pasteOnSelectToggle()
        chooserRefresh()
        return
    }
    if (choice.action !== "paste" || typeof choice.data !== "string") return

    hs.pasteboard.writeString(choice.data)
    if (previousWindow) previousWindow.focus()
    if (pasteOnSelect) {
        hs.timer.doAfter(config.pasteDelay, () => hs.eventtap.keyStroke(["cmd"], "v"))
    }
}

// MARK: - Lifecycle

function start() {
    if (chooser) return module.exports

    hs.fs.mkdir(`${hs.appinfo.configDir}/logs`)
    historyLoad()
    // Rewrite at once, so that anything password-like left on disk by an earlier run is
    // scrubbed whether or not something is copied this session.
    historySave()

    chooser = hs.chooser.create()
    chooser.placeholder = "Clipboard history"
    chooser.onSelect = chooserSelect
    chooser.onShow = () => revealKeysEnable()
    chooser.onHide = () => {
        revealKeysDisable()
        revealReset()
        // Rebuild at once, so a revealed entry is not left in the chooser's own list.
        chooserRefresh()
    }
    chooser.setChoices(chooserChoices())

    revealCurrentHotkey = hs.hotkey.create(config.revealCurrentKey.mods, config.revealCurrentKey.key,
        () => passwordRevealCurrent(), null)
    revealAllHotkey = hs.hotkey.create(config.revealAllKey.mods, config.revealAllKey.key,
        () => passwordsRevealToggle(), null)

    hs.pasteboard.watcherInterval = config.watchInterval
    watcher = () => pasteboardCapture()
    hs.pasteboard.addWatcher(watcher)

    if (config.menubarShow) {
        menubarItem = hs.menubar.create(false)
        menubarItem.title = config.menubarTitle
        menubarItem.setClickCallback(() => historyToggle())
    }

    return module.exports
}

function stop() {
    if (watcher) {
        hs.pasteboard.removeWatcher(watcher)
        watcher = null
    }
    if (chooser) {
        chooser.hide()
        chooser = null
    }
    if (revealCurrentHotkey) {
        revealCurrentHotkey.destroy()
        revealCurrentHotkey = null
    }
    if (revealAllHotkey) {
        revealAllHotkey.destroy()
        revealAllHotkey = null
    }
    if (menubarItem) {
        menubarItem.destroy()
        menubarItem = null
    }
    revealReset()
    return module.exports
}

function historyShow() {
    if (!chooser) {
        console.error("[hs_clipboard-gt] historyShow() before start()")
        return module.exports
    }
    previousWindow = hs.window.focusedWindow()
    chooserRefresh()
    chooser.show()
    return module.exports
}

function historyHide() {
    if (chooser) chooser.hide()
    return module.exports
}

function historyToggle() {
    if (!chooser) return historyShow()
    return chooser.isVisible ? historyHide() : historyShow()
}

// Reading accessors, for commands and for the console.
function historyEntries() {
    return history.map((entry) => entry.content)
}

function pasteOnSelectEnabled() {
    return pasteOnSelect
}

module.exports = {
    config,
    start,
    stop,
    historyShow,
    historyHide,
    historyToggle,
    historyClear,
    historyLastDelete,
    historyEntries,
    entryDelete,
    entryMoveToTop,
    entryMoveUp,
    entryMoveDown,
    entriesInvert,
    entriesPaste,
    pasteOnSelectToggle,
    pasteOnSelectEnabled,
    passwordLike,
    passwordRevealCurrent,
    passwordsRevealToggle
}
