// hs_clipboard-gt — a history of what has been copied, offered back through a chooser.
//
// A port of ClipboardTool.spoon (Alfred Schilken, MIT), itself derived from
// TextClipboardHistory.spoon and from code by VFS and asmagill, plus the password
// detection added to the local copy of it.
//
//     const clipboard = hs.loadSpoon("hs_clipboard-gt")
//     clipboard.start()
//     hs.hotkey.bind(hyper, "v", () => clipboard.historyShow(), null)
//
// Every string that reaches the pasteboard is prepended to the history, duplicates are
// collapsed by MD5, and the list is capped at config.historySize. Selecting an entry
// copies it back, and optionally types ⌘V into whatever window had focus.
//
// Entries that look like passwords are kept for the session but are never written to
// disk, and are shown as "[hidden - N chars]" until revealed with ⌘R (the selected row)
// or ⇧⌘R (all of them). Detection runs in three steps — an allowlist of shapes that are
// never passwords, a structural filter, and a Shannon entropy threshold — so that URLs,
// UUIDs, hashes and filenames are not masked.
//
// Four departures from the v1 Spoon:
//   * Changes arrive through hs.pasteboard.addWatcher rather than a timer of the Spoon's
//     own, so config.watchInterval sets the interval of the shared pasteboard watcher.
//   * The history is a JSON file under logs/, not an entry in the application defaults.
//   * Images are not stored. v1 kept them URL-encoded in the same list.
//   * There is no hs.dialog, so an entry longer than config.maxEntrySize is truncated
//     when it is stored instead of prompting. v1's max-size toggle is gone with it.

// MARK: - User-configurable settings

const config = {
    // Seconds between pasteboard samples. This is a property of the shared watcher, so
    // the last module to set it wins.
    watchInterval: 0.8,

    // How many entries to keep, and how much of one.
    historySize: 100,
    // Copied images, counted separately from the text entries so that a run of
    // screenshots cannot push the text out of the history. Each one is a PNG in
    // clipboardDir; the oldest is deleted as newer ones arrive.
    imageHistorySize: 10,

    // The selected image, drawn beside the chooser at a size worth looking at. The row's
    // own thumbnail is only a few points high, which is enough to tell two screenshots
    // apart but not enough to read one.
    showPreview: true,
    // Largest the preview may be, as a fraction of the usable screen height. A maximum,
    // not a target: a smaller image is drawn at its own size rather than enlarged.
    previewHeightRatio: 0.5,
    // Gap between the preview and the chooser, in points.
    previewGap: 12,
    // How far down the screen the preview sits when the chooser's own position cannot be
    // read, as a fraction of screen height.
    previewTopRatio: 0.12,
    // How often the selected row is read while the chooser is open. hs.chooser reports no
    // callback for the selection moving, so it is polled.
    previewPollSeconds: 0.15,
    maxEntrySize: 4990,

    // Characters of an entry shown in the chooser. The whole entry is copied when it is
    // selected; only the row is shortened.
    displayMaxLength: 200,

    // Whether an entry identical to one already held replaces it instead of joining it.
    deduplicate: true,

    // Whether copying announces itself, and for how long.
    copiedAlert: true,
    alertDuration: 1,

    // Whether to consult the pasteboard's data types and ignore the entry when one of
    // them is in ignoredIdentifiers. The list comes from http://nspasteboard.org.
    honorIgnoredIdentifiers: true,
    ignoredIdentifiers: [
        "de.petermaurer.TransientPasteboardType", // Transient: Textpander, TextExpander, Butler
        "com.typeit4me.clipping",                 // Transient: TypeIt4Me
        "Pasteboard generator type",              // Transient: Typinator
        "com.agilebits.onepassword",              // Confidential: 1Password
        "org.nspasteboard.TransientType",         // Universal, transient
        "org.nspasteboard.ConcealedType",         // Universal, concealed
        "org.nspasteboard.AutoGeneratedType"      // Universal, automatic
    ],

    // Password-like entries: masked in the chooser and never persisted. Setting this to
    // false persists everything and masks nothing.
    passwordsHide: true,
    passwordEntropyThreshold: 3.5,
    passwordMinLength: 8,
    passwordMaxNewlines: 1,

    // Chords that reveal a masked entry, active only while the chooser is on screen.
    revealCurrentKey: {mods: ["cmd"], key: "r"},
    revealAllKey: {mods: ["cmd", "shift"], key: "r"},

    // Seconds to wait after the chooser closes before typing, so that the keystrokes
    // arrive at the window that has just regained focus.
    pasteDelay: 0.2,

    // The menubar item, which opens the history when clicked.
    menubarShow: true,
    menubarTitle: "📋",

    // Where the history and the copied images live. The images are files, so they need a
    // directory of their own rather than a corner of logs/, and the history moved in
    // beside them so that everything this Spoon keeps is in one place.
    clipboardDir: `${hs.appinfo.configDir}/clipboard`,
    historyFile: `${hs.appinfo.configDir}/clipboard/clipboard.json`,
    // Where a version before this one kept the history. Moved on the first start that
    // finds it.
    historyFileWas: `${hs.appinfo.configDir}/logs/clipboard.json`
}

// MARK: - State

// [{type: "text", content: "..."}], most recent first.
let history = []

// Whether selecting an entry also types ⌘V. Persisted alongside the history.
let pasteOnSelect = false

let chooser = null
let menubarItem = null
let watcher = null

// The window that had focus when the chooser was shown. The chooser takes focus itself,
// so anything typed afterwards needs it restored first.
let previousWindow = null

// Reveal state, reset every time the chooser closes.
let revealAll = false
let revealedRow = null
let revealCurrentHotkey = null
let revealAllHotkey = null

// MARK: - Password detection

// Shannon entropy of a string, in bits per character.
function passwordEntropy(text) {
    if (!text || text.length === 0) return 0

    const counts = new Map()
    for (const character of text) counts.set(character, (counts.get(character) || 0) + 1)

    let entropy = 0
    for (const count of counts.values()) {
        const p = count / text.length
        entropy -= p * Math.log2(p)
    }
    return entropy
}

const PASSWORD_SYMBOLS = /[!@#$%^&*()\-_=+[\]{}|;:',.<>?/\\`~"]/
// Above this share of digits, or of hex characters, a string is an identifier of some
// kind rather than a password.
const PASSWORD_MOSTLY = 0.70

// Step 1: shapes that are never masked, however random they look.
function passwordAllowlisted(text) {
    const length = text.length

    if ((text.match(/\n/g) || []).length > config.passwordMaxNewlines) return true

    // UUID.
    if (/^[0-9a-fA-F]{1,8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/.test(text)) return true
    // ULID: 26 characters of Crockford Base32.
    if (length === 26 && /^[0-9A-HJKMNP-TV-Z]+$/.test(text)) return true
    // MD5, SHA1 or SHA256 written out in hex.
    if ((length === 32 || length === 40 || length === 64) && /^[0-9a-fA-F]+$/.test(text)) return true
    // Base64 with padding.
    if (length % 4 === 0 && /=+$/.test(text) && /^[A-Za-z0-9+/]+=*$/.test(text)) return true
    // A number.
    if (/^-?[0-9]+\.?[0-9]*$/.test(text)) return true
    // An ISO date, with or without a time after it.
    if (/^\d{4}-\d{2}-\d{2}/.test(text)) return true
    // IPv4, and IPv6 taken as hex with at least two colons in it.
    if (/^\d+\.\d+\.\d+\.\d+$/.test(text)) return true
    if (/^[0-9a-fA-F:]+$/.test(text) && /:.*:/.test(text)) return true
    // A URL, a path, or a bare filename.
    if (text.includes("://")) return true
    if (text.includes("/")) return true
    if (/\.[a-zA-Z0-9]+$/.test(text) && !/\s/.test(text)) return true

    return false
}

// Step 2: long enough, unbroken, and mixed enough to be a password.
function passwordStructured(text) {
    const length = text.length
    if (length < config.passwordMinLength) return false
    if (/\s/.test(text)) return false

    let digits = 0
    let hex = 0
    let lower = false
    let upper = false
    let digit = false
    let symbol = false

    for (const character of text) {
        if (/[0-9]/.test(character)) {
            digits += 1
            hex += 1
            digit = true
        } else if (/[a-f]/.test(character)) {
            hex += 1
            lower = true
        } else if (/[A-F]/.test(character)) {
            hex += 1
            upper = true
        } else if (/[a-z]/.test(character)) {
            lower = true
        } else if (/[A-Z]/.test(character)) {
            upper = true
        } else if (PASSWORD_SYMBOLS.test(character)) {
            symbol = true
        }
    }

    if (digits / length >= PASSWORD_MOSTLY) return false
    if (hex / length >= PASSWORD_MOSTLY) return false

    const classes = [lower, upper, digit, symbol].filter(Boolean).length
    return classes >= 2
}

// All three steps. Only a string that clears every one of them is treated as a password.
function passwordLike(text) {
    if (typeof text !== "string" || text === "") return false
    if (passwordAllowlisted(text)) return false
    if (!passwordStructured(text)) return false
    return passwordEntropy(text) >= config.passwordEntropyThreshold
}

// The preview canvas beside the chooser, the row it is showing, and the timer that reads
// the selection. Held so they cannot be collected before they are used again.
let preview = null
let previewRow = null
let previewTimer = null

// The last image written back to the pasteboard by this Spoon, so that the change it
// causes is not stored again. Compared by size, which is enough to tell a fresh copy of
// something else from the image just pasted.
let lastImageWritten = null
let lastImageWrittenSize = null

/** Whether the image on the pasteboard is not the one this Spoon last wrote. */
function pasteboardImageIsNew() {
    if (!lastImageWrittenSize) return true
    const image = hs.pasteboard.readImage()
    if (!image || !image.size) return true
    return Math.round(image.size.w) !== lastImageWrittenSize.w ||
        Math.round(image.size.h) !== lastImageWrittenSize.h
}

// MARK: - Persistence

function historyLoad() {
    if (!hs.fs.exists(config.historyFile)) return

    const body = hs.fs.read(config.historyFile, 0, 0)
    if (!body || body === "") return

    let data = null
    try {
        data = JSON.parse(body)
    } catch (error) {
        console.error(`[hs_clipboard-gt] ${config.historyFile} is unreadable, starting fresh: ${error}`)
        return
    }
    if (!data || typeof data !== "object") return

    pasteOnSelect = data.pasteOnSelect === true
    history = historyPrune(Array.isArray(data.items) ? data.items : [])
}

// Password-like entries live in memory only, so they are dropped on the way out. This
// also scrubs any that an earlier version of the Spoon, or of its v1 ancestor, wrote.
function historySave() {
    const items = config.passwordsHide
        ? history.filter((entry) => entry.type === "image" || !passwordLike(entry.content))
        : history
    hs.fs.write(config.historyFile,
        JSON.stringify({pasteOnSelect: pasteOnSelect, items: items}, null, 2), false)
}

// MARK: - The history itself

// Discards malformed entries, collapses duplicates and applies the size caps. The first
// of a set of duplicates wins, so the most recent copy keeps its place at the top.
//
// Text and images are counted separately: a burst of screenshots would otherwise evict
// the text history, and the two are not interchangeable. Order is preserved across both,
// so the list still reads newest first whatever the entries are.
//
// An image that falls off the end takes its file with it; see imagesSweep().
function historyPrune(list) {
    const result = []
    const seen = new Set()
    let texts = 0
    let images = 0

    for (const entry of list) {
        if (!entry) continue

        if (entry.type === "image") {
            if (images >= config.imageHistorySize) continue
            if (typeof entry.path !== "string" || !hs.fs.exists(entry.path)) continue
            images += 1
            result.push({
                type: "image",
                path: entry.path,
                width: entry.width || 0,
                height: entry.height || 0
            })
            continue
        }

        if (entry.type !== "text" || typeof entry.content !== "string") continue
        if (texts >= config.historySize) continue

        const hash = hs.hashing.md5(entry.content)
        if (config.deduplicate && seen.has(hash)) continue

        seen.add(hash)
        texts += 1
        result.push({type: "text", content: entry.content})
    }
    return result
}

/**
 * Delete the image files in clipboardDir that no entry refers to any more.
 *
 * Called after the history changes, so the directory holds what the history holds and no
 * more. A file that will not go is left for the next sweep.
 *
 * @returns {number} How many files were deleted.
 */
function imagesSweep() {
    const wanted = new Set(history.filter((e) => e.type === "image").map((e) => e.path))
    const names = hs.fs.list(config.clipboardDir) || []
    let removed = 0

    for (const name of names) {
        if (!/\.png$/.test(name)) continue
        const path = `${config.clipboardDir}/${name}`
        if (wanted.has(path)) continue
        if (hs.fs.deletePath(path)) removed += 1
    }
    return removed
}

// Cuts an over-long entry at the last blank line that fits, and failing that at the
// limit itself.
function contentTruncate(text) {
    if (text.length <= config.maxEntrySize) return text

    const paragraph = text.lastIndexOf("\n\n", config.maxEntrySize)
    return paragraph > 0 ? text.slice(0, paragraph) : text.slice(0, config.maxEntrySize)
}

function historyAdd(text) {
    history.unshift({type: "text", content: text})
    history = historyPrune(history)
    historySave()
}

// MARK: - Reading the pasteboard

function pasteboardIgnored() {
    if (!config.honorIgnoredIdentifiers) return false
    return (hs.pasteboard.types() || []).some((type) => config.ignoredIdentifiers.includes(type))
}

/** Whether the pasteboard is offering an image, by type rather than by guessing. */
function pasteboardHasImage() {
    for (const type of ["public.png", "public.tiff", "public.jpeg"]) {
        try {
            if (hs.pasteboard.hasType(type)) return true
        } catch (e) { /* try the next */ }
    }
    return false
}

/**
 * Store the image on the pasteboard as a file, and put an entry at the top of the history.
 *
 * The file is named for the time it was copied, which sorts and reads well in a directory
 * listing, and makes two copies in the same second the only collision to worry about.
 */
function imageCapture() {
    const image = hs.pasteboard.readImage()
    if (!image) return false

    hs.fs.mkdir(config.clipboardDir)

    const stamp = new Date().toISOString().replace(/[-:]/g, "").replace(/\..+$/, "")
    const path = `${config.clipboardDir}/${stamp}.png`

    if (!image.saveToFile(path)) {
        console.error(`[hs_clipboard-gt] could not write ${path}`)
        return false
    }

    const size = image.size
    history.unshift({
        type: "image",
        path: path,
        width: size ? Math.round(size.w) : 0,
        height: size ? Math.round(size.h) : 0
    })
    history = historyPrune(history)
    historySave()
    imagesSweep()

    // Remembered so that writing this image back to the pasteboard, which arrives here as
    // a change of its own, is not stored a second time.
    lastImageWritten = path

    if (config.copiedAlert) {
        const dimensions = size ? `${Math.round(size.w)}x${Math.round(size.h)}` : "an image"
        hs.ui.alert(`Copied ${dimensions} image`).duration(config.alertDuration).show()
    }
    return true
}

function pasteboardCapture() {
    if (pasteboardIgnored()) return

    // An image the Spoon itself just wrote back arrives here as a change; nothing was
    // copied, so there is nothing to store or announce.
    if (pasteboardHasImage()) {
        if (lastImageWritten && !pasteboardImageIsNew()) return
        imageCapture()
        return
    }

    const content = hs.pasteboard.readString()
    if (content === null || content === undefined || content === "") return

    // Selecting an entry writes it back to the pasteboard, which arrives here as a
    // change of its own. Nothing has been copied, so there is nothing to announce.
    if (history.length > 0 && history[0].content === content) return

    const stored = contentTruncate(content)
    historyAdd(stored)

    if (!config.copiedAlert) return
    const masked = config.passwordsHide && passwordLike(stored)
    const note = masked ? " (password-like, not persisted)" : ""
    const shortened = stored.length < content.length ? ` of ${content.length}` : ""
    hs.ui.alert(`Copied ${stored.length}${shortened} chars${note}`).duration(config.alertDuration).show()
}

// MARK: - Typing and pasting

// The chooser holds focus while it is up, so anything typed has to wait for the window
// underneath to have it back.
function windowRestore(then) {
    if (chooser && chooser.isVisible) chooser.hide()
    if (previousWindow) previousWindow.focus()
    hs.timer.doAfter(config.pasteDelay, then)
}

// v1's "paste all with delimiter": every entry from the given row up to the newest one,
// typed out oldest first, each followed by the delimiter.
function entriesPaste(row, delimiter) {
    const entries = history.slice(0, row + 1).reverse()
    windowRestore(() => {
        for (const entry of entries) {
            // An image cannot be typed, so it is passed over rather than stopping the run.
            if (entry.type === "image") continue
            hs.eventtap.keyStrokes(entry.content)
            hs.eventtap.keyStrokes(delimiter)
        }
    })
}

// MARK: - Rearranging entries

function entryDelete(row) {
    if (row < 0 || row >= history.length) return module.exports
    history.splice(row, 1)
    historySave()
    chooserRefresh()
    return module.exports
}

function entryMove(row, destination) {
    if (row < 0 || row >= history.length) return module.exports
    const target = Math.min(Math.max(destination, 0), history.length - 1)
    if (target === row) return module.exports

    const [entry] = history.splice(row, 1)
    history.splice(target, 0, entry)
    historySave()
    chooserRefresh()
    return module.exports
}

function entryMoveToTop(row) { return entryMove(row, 0) }
function entryMoveUp(row) { return entryMove(row, row - 1) }
function entryMoveDown(row) { return entryMove(row, row + 1) }

// Reverses the order of everything from the newest entry down to the given row, which is
// what v1 offered for turning a set of copies back into the order they were made in.
function entriesInvert(row) {
    if (row < 0 || row >= history.length) return module.exports
    const head = history.slice(0, row + 1).reverse()
    history = head.concat(history.slice(row + 1))
    historySave()
    chooserRefresh()
    return module.exports
}

function historyClear() {
    hs.pasteboard.clear()
    history = []
    historySave()
    chooserRefresh()
    return module.exports
}

function historyLastDelete() {
    return entryDelete(0)
}

// MARK: - Paste-on-select

function pasteOnSelectToggle() {
    pasteOnSelect = !pasteOnSelect
    historySave()
    hs.ui.alert(`Paste-on-select is now ${pasteOnSelect ? "enabled" : "disabled"}`)
        .duration(config.alertDuration).show()
    return pasteOnSelect
}

// MARK: - Revealing masked entries

function revealReset() {
    revealAll = false
    revealedRow = null
}

// ⌘R: reveal the selected row, or hide it again if it is the one already revealed.
function passwordRevealCurrent() {
    if (!chooser) return module.exports
    const row = chooser.selectedRow
    if (row === null || row === undefined || row < 0) return module.exports

    revealedRow = revealedRow === row ? null : row
    chooserRefresh()
    chooser.selectedRow = row
    return module.exports
}

// ⇧⌘R: reveal every masked entry, or mask them all again.
function passwordsRevealToggle() {
    if (!chooser) return module.exports
    const row = chooser.selectedRow

    revealAll = !revealAll
    revealedRow = null
    chooserRefresh()
    if (row !== null && row !== undefined && row >= 0) chooser.selectedRow = row
    return module.exports
}

function revealKeysEnable() {
    if (revealCurrentHotkey) revealCurrentHotkey.enable()
    if (revealAllHotkey) revealAllHotkey.enable()
}

function revealKeysDisable() {
    if (revealCurrentHotkey) revealCurrentHotkey.disable()
    if (revealAllHotkey) revealAllHotkey.disable()
}

// MARK: - The preview
//
// The selected image, drawn on a canvas to the left of the chooser. A row's own image is a
// few points high, which distinguishes two screenshots but does not let you read either.
//
// The same approach as the window preview in hs_selectWindow-gt, and the second use of it.
// If a third appears it is worth extracting: the sizing, the placement and the polling are
// not specific to what the picture is of.

const HAMMERSPOON_BUNDLE_ID = "net.tenshu.Hammerspoon-2"

/**
 * Where the chooser is, so the preview can sit beside it.
 *
 * Its width and left edge follow from hs.chooser centring a window of the configured
 * width. Its vertical position does not, and hs.chooser reports no frame, so it is read
 * from Hammerspoon's own window list: the chooser is the window whose left edge and width
 * match the computed ones, which separates it from the console and from this canvas.
 *
 * Asking one application for its windows costs about 10ms.
 */
function chooserGeometry(area) {
    const width = area.w * (chooser && chooser.width ? chooser.width : 0.5)
    const left = area.x + (area.w - width) / 2
    let top = area.y + area.h * config.previewTopRatio

    try {
        const app = hs.application.matchingBundleID(HAMMERSPOON_BUNDLE_ID)
        for (const window of (app ? app.allWindows || [] : [])) {
            const frame = window.frame
            if (!frame) continue
            if (Math.abs(frame.x - left) <= 2 && Math.abs(frame.w - width) <= 2) {
                top = frame.y
                break
            }
        }
    } catch (e) {
        // The computed position stands.
    }

    return { left: left, width: width, top: top }
}

/** Where to draw a preview of this image, or null when there is nowhere sensible. */
function previewFrame(image) {
    const screen = hs.screen.main() || hs.screen.primary()
    const reference = hs.screen.primary() || screen
    if (!screen || !reference) return null

    const area = screen.frame
    const size = image.size
    if (!size || !size.w || !size.h) return null

    // A maximum rather than a target: a small image drawn at four times its size is a
    // blurred rectangle, and says less than the same image drawn honestly.
    let height = Math.min(area.h * config.previewHeightRatio, size.h)
    let width = size.w * (height / size.h)

    const geometry = chooserGeometry(area)
    const available = (geometry.left - area.x) - config.previewGap * 2
    if (available > 0 && width > available) {
        height = height * (available / width)
        width = available
    }

    const left = geometry.left - config.previewGap - width
    const top = geometry.top

    // hs.screen measures y downwards from the top of the primary display and a canvas
    // upwards from its bottom.
    return {
        x: left,
        y: (reference.fullFrame.y + reference.fullFrame.h) - (top + height),
        w: width,
        h: height
    }
}

function previewHide() {
    if (!preview) return
    preview.destroy()
    preview = null
    previewRow = null
}

function previewDraw(image, row) {
    previewHide()
    if (!image) return

    const frame = previewFrame(image)
    if (!frame) return

    preview = hs.canvas.create(frame)
        .level("popUpMenu")
        .ignoreMouseEvents(true)
        .behaviorList(["canJoinAllSpaces", "stationary"])

    preview.appendElements([
        {
            type: "rectangle",
            action: "fill",
            fillColor: { red: 0, green: 0, blue: 0, alpha: 0.55 },
            frame: { x: 0, y: 0, w: frame.w, h: frame.h },
            roundedRectRadii: { xRadius: 10, yRadius: 10 }
        },
        {
            type: "image",
            image: image,
            frame: { x: 4, y: 4, w: frame.w - 8, h: frame.h - 8 },
            imageScaling: "scaleProportionally",
            imageAlignment: "center"
        }
    ])
    preview.show()
    previewRow = row
}

/** The history row the chooser has selected, or null. */
function selectedRow() {
    if (!chooser || !chooser.isVisible) return null
    const contents = chooser.selectedRowContents(chooser.selectedRow)
    return contents && contents.row !== undefined ? contents.row : null
}

/** Draw, redraw or take away the preview, according to what is selected now. */
function previewUpdate() {
    if (!config.showPreview) return
    if (!chooser || !chooser.isVisible) {
        previewHide()
        return
    }

    const row = selectedRow()
    if (row === null) {
        previewHide()
        return
    }
    if (row === previewRow) return

    const entry = history[row]
    if (!entry || entry.type !== "image") {
        previewHide()
        return
    }

    const image = HSImage.fromPath(entry.path)
    if (!image) {
        previewHide()
        return
    }
    previewDraw(image, row)
}

function previewPollStart() {
    previewPollStop()
    if (!config.showPreview) return
    previewTimer = hs.timer.doEvery(config.previewPollSeconds, () => previewUpdate())
}

function previewPollStop() {
    if (!previewTimer) return
    previewTimer.stop()
    previewTimer = null
}

// MARK: - The chooser

// Right-clicking a row offers what v1 put behind its own context menu. The row is fixed
// when the menu is built, so every action closes over it.
function entryContextMenu(row) {
    return [
        {title: "Paste all up to here, tab separated", action: () => entriesPaste(row, "\t")},
        {title: "Paste all up to here, one per line", action: () => entriesPaste(row, "\n")},
        {type: "divider"},
        {title: "Delete entry", action: () => entryDelete(row)},
        {title: "Move entry to top", action: () => entryMoveToTop(row)},
        {title: "Move entry up", action: () => entryMoveUp(row)},
        {title: "Move entry down", action: () => entryMoveDown(row)},
        {title: "Invert order above", action: () => entriesInvert(row)}
    ]
}

function chooserChoices() {
    const choices = []

    history.forEach((entry, row) => {
        if (entry.type === "image") {
            // The picture itself is the row's image, so the entry is recognisable without
            // reading anything. The chooser scales it to the row.
            choices.push({
                text: `${entry.width}x${entry.height} image`,
                subText: entry.path.split("/").pop(),
                image: HSImage.fromPath(entry.path),
                action: "pasteImage",
                data: entry.path,
                row: row,
                contextMenu: entryContextMenu(row)
            })
            return
        }

        const masked = config.passwordsHide && passwordLike(entry.content)
        const revealed = revealAll || revealedRow === row
        const text = (masked && !revealed)
            ? `[hidden - ${entry.content.length} chars]`
            : entry.content.slice(0, config.displayMaxLength)

        choices.push({
            text: text,
            action: "paste",
            data: entry.content,
            row: row,
            contextMenu: entryContextMenu(row)
        })
    })

    if (choices.length === 0) {
        choices.push({
            text: "",
            subText: "《Clipboard is empty》",
            action: "none",
            image: HSImage.fromName("NSCaution")
        })
    } else {
        choices.push({
            text: "《Clear Clipboard History》",
            action: "clear",
            image: HSImage.fromName("NSTrashFull")
        })
    }

    choices.push({
        text: `《${pasteOnSelect ? "Disable" : "Enable"} Paste-on-select》`,
        action: "pasteOnSelect",
        // v1 used NSSwitchEnabledOn/Off, which this macOS no longer resolves.
        image: HSImage.fromSymbol(pasteOnSelect ? "checkmark.circle.fill" : "circle")
    })

    return choices
}

function chooserRefresh() {
    if (chooser) chooser.setChoices(chooserChoices())
    return module.exports
}

function chooserSelect(choice) {
    revealKeysDisable()
    revealReset()

    if (!choice) return

    if (choice.action === "clear") {
        historyClear()
        return
    }
    if (choice.action === "pasteOnSelect") {
        pasteOnSelectToggle()
        chooserRefresh()
        return
    }
    previewPollStop()
    previewHide()

    if (choice.action === "pasteImage" && typeof choice.data === "string") {
        const image = HSImage.fromPath(choice.data)
        if (!image) {
            hs.ui.alert("That image is no longer on disk").duration(2).show()
            return
        }
        lastImageWritten = choice.data
        lastImageWrittenSize = image.size
            ? {w: Math.round(image.size.w), h: Math.round(image.size.h)}
            : null
        hs.pasteboard.writeImage(image)
        if (previousWindow) previousWindow.focus()
        if (pasteOnSelect) {
            hs.timer.doAfter(config.pasteDelay, () => hs.eventtap.keyStroke(["cmd"], "v"))
        }
        return
    }

    if (choice.action !== "paste" || typeof choice.data !== "string") return

    hs.pasteboard.writeString(choice.data)
    if (previousWindow) previousWindow.focus()
    if (pasteOnSelect) {
        hs.timer.doAfter(config.pasteDelay, () => hs.eventtap.keyStroke(["cmd"], "v"))
    }
}

// MARK: - Lifecycle

function start() {
    if (chooser) return module.exports

    hs.fs.mkdir(config.clipboardDir)

    // An earlier version kept the history under logs/. Moved, rather than read in place,
    // so that everything this Spoon owns ends up in one directory.
    if (!hs.fs.exists(config.historyFile) && hs.fs.exists(config.historyFileWas)) {
        if (hs.fs.move(config.historyFileWas, config.historyFile)) {
            console.log(`[hs_clipboard-gt] history moved to ${config.historyFile}`)
        } else {
            console.error(`[hs_clipboard-gt] could not move ${config.historyFileWas}`)
        }
    }
    historyLoad()
    // Rewrite at once, so that anything password-like left on disk by an earlier run is
    // scrubbed whether or not something is copied this session.
    historySave()

    chooser = hs.chooser.create()
    chooser.placeholder = "Clipboard history"
    chooser.onSelect = chooserSelect
    chooser.onShow = () => {
        revealKeysEnable()
        previewPollStart()
    }
    chooser.onHide = () => {
        revealKeysDisable()
        revealReset()
        previewPollStop()
        previewHide()
        // Rebuild at once, so a revealed entry is not left in the chooser's own list.
        chooserRefresh()
    }
    chooser.setChoices(chooserChoices())

    revealCurrentHotkey = hs.hotkey.create(config.revealCurrentKey.mods, config.revealCurrentKey.key,
        () => passwordRevealCurrent(), null)
    revealAllHotkey = hs.hotkey.create(config.revealAllKey.mods, config.revealAllKey.key,
        () => passwordsRevealToggle(), null)

    hs.pasteboard.watcherInterval = config.watchInterval
    watcher = () => pasteboardCapture()
    hs.pasteboard.addWatcher(watcher)

    if (config.menubarShow) {
        menubarItem = hs.menubar.create(false)
        menubarItem.title = config.menubarTitle
        menubarItem.setClickCallback(() => historyToggle())
    }

    return module.exports
}

function stop() {
    previewPollStop()
    previewHide()
    if (watcher) {
        hs.pasteboard.removeWatcher(watcher)
        watcher = null
    }
    if (chooser) {
        chooser.hide()
        chooser = null
    }
    if (revealCurrentHotkey) {
        revealCurrentHotkey.destroy()
        revealCurrentHotkey = null
    }
    if (revealAllHotkey) {
        revealAllHotkey.destroy()
        revealAllHotkey = null
    }
    if (menubarItem) {
        menubarItem.destroy()
        menubarItem = null
    }
    revealReset()
    return module.exports
}

function historyShow() {
    if (!chooser) {
        console.error("[hs_clipboard-gt] historyShow() before start()")
        return module.exports
    }
    previousWindow = hs.window.focusedWindow()
    chooserRefresh()
    chooser.show()
    return module.exports
}

function historyHide() {
    if (chooser) chooser.hide()
    return module.exports
}

function historyToggle() {
    if (!chooser) return historyShow()
    return chooser.isVisible ? historyHide() : historyShow()
}

// Reading accessors, for commands and for the console.
function historyEntries() {
    return history.map((entry) => entry.type === "image"
        ? `[image ${entry.width}x${entry.height}] ${entry.path}`
        : entry.content)
}

function pasteOnSelectEnabled() {
    return pasteOnSelect
}

module.exports = {
    config,
    start,
    stop,
    historyShow,
    historyHide,
    historyToggle,
    historyClear,
    historyLastDelete,
    historyEntries,
    entryDelete,
    entryMoveToTop,
    entryMoveUp,
    entryMoveDown,
    entriesInvert,
    entriesPaste,
    pasteOnSelectToggle,
    pasteOnSelectEnabled,
    passwordLike,
    passwordRevealCurrent,
    passwordsRevealToggle
}
